
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: udemy_clone_development

test:
  <<: *default
  database: udemy_clone_test

production:
  <<: *default
  database: udemy_clone_production
  username: udemy_clone
  password: <%= ENV['UDEMY_CLONE_DATABASE_PASSWORD'] %>
